### PR TITLE
#63 Fixed Readme nd ORMSchemaEventListener.

### PR DESCRIPTION
**Pull request by tasselchof**
Fixes in README and listener.

### CODE REVIEW

**Comment by GwendolenLynch** [comment]
Thank you @tasselchof, I appreciate your effort.

However, the problem was pure documentation. Specifically, as its name implies it is a listener, so it needed `addListener('postGenerateSchemaTable', …`. I have pushed that and one other `README.md` change in https://github.com/GwendolenLynch/doctrine-postgis/commit/c2b86ffd39ddb7f8d4ea650e25cbda9dd4d7ea38

**Comment by tasselchof** [comment]
> Thank you @tasselchof, I appreciate your effort.
> 
> However, the problem was pure documentation. Specifically, as its name implies it is a listener, so it needed `addListener('postGenerateSchemaTable', …`. I have pushed that and one other `README.md` change in [c2b86ff](https://github.com/GwendolenLynch/doctrine-postgis/commit/c2b86ffd39ddb7f8d4ea650e25cbda9dd4d7ea38)

Not only that, the listener itself should implement EventSubscriber, otherwise it was not working.

Thanks!

**Comment by GwendolenLynch** [comment]
It should work without the contract, see https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/events.html

Are you sure you're not still calling `addSubscriber()` instead of `addListener()`? As that would give the error you describe.

**Comment by tasselchof** [comment]
> It should work without the contract, see https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/events.html
> 
> Are you sure you're not still calling `addSubscriber()` instead of `addListener()`? As that would give the error you describe.

Frankly speaking, I am working on moving the current application which is done using Laminas to a new platform. We have a config and those subscribers were added through configuration, not by addListener or addEvent. Judging by the key name in the configuration it's subscriber. I was getting this exception after the update:

```
[dev@de1 api]$ ./bin/doctrine orm:schema-tool:update --dump-sql --complete
PHP Fatal error:  Uncaught Roave\PsrContainerDoctrine\Exception\DomainException: Invalid event subscriber "Jsor\Doctrine\PostGIS\Event\ORMSchemaEventListener" given, must be a dependency name, class name or an instance implementing Doctrine\Common\EventSubscriber in /home/dev/domains/api/vendor/roave/psr-container-doctrine/src/Exception/DomainException.php:36
```

So I added the contract and everything worked after this.

**Comment by tasselchof** [comment]
I've checked it, this way:
```
'event_manager' => [
            'orm_default' => [
                'listeners' => [
                    [
                        'listener' => ORMSchemaEventListener::class,
                        'events' => [
                            'postGenerateSchemaTable',
                        ],
                    ]
                ],
            ],
        ],
```

It won't give an exception, but isn't it better to have it like that:
```
'event_manager' => [
            'orm_default' => [
                'subscribers' => [
                    ORMSchemaEventListener::class,
                ],
            ],
        ],
```

As a subscriber with a contract? I know this is bad, but with this interface it is working both ways.

**Comment by GwendolenLynch** [comment]
> Frankly speaking, I am working on moving the current application which is done using Laminas to a new platform. 

Oh yes, migrations are always full of unexpected "fun". 

> As a subscriber with a contract? 

I am not fully up-to-date on what is happening in Doctrine Land right now, but the subscribers are supposed to be on the list to be deprecated. To that end I implemented it to be a listener.

> I know this is bad, but with this interface it is working both ways.

Exactly, is bad design. Essentially the problem is still a documentation one, a need for similar to `docs/symfony.md`, and I would be very happy for you to PR that. :+1:

**Pull request closed without merging**
